export const productData = [
    {
        categoryName: 'slimdrawerbox',
        name: 'slim Drawer Box',
        description:
            'Lorem Ipsum has been the industrys standard dummy text ever since the 1500s.',
        price: 250,
        sku: 'slimdrawerbox',
        id: 1,
        image: '/Images/slimdrawerbox.jpeg',
        qty: 25,
        rating: 5,
        stock: 'IN_STOCK',
    },
    {
        categoryName: 'slimdrawerbox',
        name: 'Slim Drawer Box1',
        description:
            'Lorem Ipsum has been the industrys standard dummy text ever since the 1500s.',
        price: 200,
        sku: 'slimdrawerbox',
        id: 2,
        image: '/Images/slimdrawerbox.jpeg',
        qty: 25,
        rating: 5,
        stock: 'OUT_OF_STOCK',
    },
    {
        categoryName: 'tandomdrawerbox',
        name: 'Tandom Drawer Box',
        description:
            'Lorem Ipsum has been the industrys standard dummy text ever since the 1500s.',
        price: 280,
        id: 3,
        sku: 'tandomdrawerbox',
        image: '/Images/tandomdrawerbox.png',
        qty: 25,
        rating: 5,
        stock: 'IN_STOCK',
    },
    {
        categoryName: 'pulldown',
        name: 'Pull Down',
        description:
            'Lorem Ipsum has been the industrys standard dummy text ever since the 1500s.',
        price: 300,
        id: 4,
        sku: 'pulldown',
        image: '/Images/pulldown.jpg',
        qty: 25,
        rating: 5,
        stock: 'IN_STOCK',
    },
    {
        categoryName: 'cutlery',
        name: 'Cutlery',
        description:
            'Lorem Ipsum has been the industrys standard dummy text ever since the 1500s.',
        price: 350,
        id: 5,
        sku: 'cutlery',
        image: '/Images/cutlery.jpeg',
        qty: 25,
        rating: 5,
        stock: 'IN_STOCK',
    },
    {
        categoryName: 'pantry',
        name: 'Pantry',
        description:
            'Lorem Ipsum has been the industrys standard dummy text ever since the 1500s.',
        price: 400,
        sku: 'pantry',
        id: 6,
        image: '/Images/pantry.jpg',
        qty: 25,
        rating: 5,
        stock: 'IN_STOCK',
    },
    {
        categoryName: 'elevator',
        name: 'Elevator',
        description:
            'Lorem Ipsum has been the industrys standard dummy text ever since the 1500s.',
        price: 450,
        sku: 'elevator',
        id: 7,
        image: '/Images/elevator.jpg',
        qty: 25,
        rating: 5,
        stock: 'IN_STOCK',
    },
    {
        categoryName: 'quadrochannel',
        name: 'Quadro Channel',
        description:
            'Lorem Ipsum has been the industrys standard dummy text ever since the 1500s.',
        price: 500,
        sku: 'quadrochannel',
        id: 8,
        image: '/Images/quadrochannel.jpg',
        qty: 25,
        rating: 5,
        stock: 'IN_STOCK',
    },
    {
        categoryName: 'kitchenaccesories',
        name: 'Kitchen Accesories',
        description:
            'Lorem Ipsum has been the industrys standard dummy text ever since the 1500s.',
        price: 550,
        id: 9,
        sku: 'kitchenaccesories',
        image: '/Images/kitchenaccesories.jpeg',
        qty: 25,
        rating: 5,
        stock: 'IN_STOCK',
    },
    {
        categoryName: 'hingeseriesunit',
        name: 'Hingeseries Unit',
        description:
            'Lorem Ipsum has been the industrys standard dummy text ever since the 1500s.',
        price: 600,
        id: 10,
        sku: 'hingeseriesunit',
        image: '/Images/hingeseriesunit.jpg',
        qty: 25,
        rating: 5,
        stock: 'IN_STOCK',
    },
    {
        categoryName: 'rollingshutterbasket',
        name: 'Rolling Shutter Basket',
        description:
            'Lorem Ipsum has been the industrys standard dummy text ever since the 1500s.',
        price: 650,
        id: 11,
        sku: 'rollingshutterbasket',
        image: '/Images/rollingshutterbasket.jpeg',
        qty: 25,
        rating: 5,
        stock: 'IN_STOCK',
    },
    {
        categoryName: 'doorcloser',
        name: 'Door Closer',
        description:
            'Lorem Ipsum has been the industrys standard dummy text ever since the 1500s.',
        price: 700,
        sku: 'doorcloser',
        id: 12,
        image: '/Images/doorcloser.jpg',
        qty: 25,
        rating: 5,
        stock: 'IN_STOCK',
    },
    {
        categoryName: 'accesories',
        name: 'Accesories',
        description:
            'Lorem Ipsum has been the industrys standard dummy text ever since the 1500s.',
        price: 750,
        sku: 'accesories',
        image: '/Images/kitchenaccesories.jpeg',
        id: 13,
        qty: 25,
        rating: 5,
        stock: 'IN_STOCK',
    },
    {
        categoryName: 'cornersolution',
        name: 'Cornersolution',
        description:
            'Lorem Ipsum has been the industrys standard dummy text ever since the 1500s.',
        price: 800,
        sku: 'cornersolution',
        image: '/Images/cornersolution.jpg',
        id: 14,
        qty: 25,
        rating: 5,
        stock: 'IN_STOCK',
    },
    {
        categoryName: 'tallunit',
        name: 'Tall Unit',
        description:
            'Lorem Ipsum has been the industrys standard dummy text ever since the 1500s.',
        price: 850,
        sku: 'tallunit',
        image: '/Images/tallunit.jpg',
        id: 15,
        qty: 25,
        rating: 5,
        stock: 'IN_STOCK',
    },
]
